import { useState } from 'react'
import type { ErpData, PaymentMethod } from '../../types'
import type { PayableInput } from '../../services/finance'
import { MoneyInput } from '../../components/MoneyInput'
import { parseInvoicePhotoText, parseSupplierInvoiceXml, type ImportedInvoice, type SupplierCostCategory } from '../../services/supplierInvoiceImport'
export function SupplierInvoiceCapture({data,onSave}:{data:ErpData;onSave:(input:PayableInput)=>void}) {
 const [draft,setDraft]=useState<ImportedInvoice|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[preview,setPreview]=useState('')
 const read=async(file:File)=>{
  setDraft(null);setPreview('');setBusy(true);setMessage('Lettura documento…')
  try{
   if(file.size>12_000_000)throw new Error('File troppo grande: massimo 12 MB.')
   if(file.name.toLowerCase().endsWith('.xml')) {setDraft(parseSupplierInvoiceXml(await file.text()));setMessage('XML letto. Controlla categorie e scadenze, poi conferma.');return}
   if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Usa XML, JPG, PNG o WebP. Per un PDF puoi fotografare la pagina oppure usare l’XML originale.')
   const image=await createImageBitmap(file);const ratio=Math.min(1,2000/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*ratio);canvas.height=Math.round(image.height*ratio);const context=canvas.getContext('2d');if(!context)throw new Error('Fotografia non leggibile.');context.drawImage(image,0,0,canvas.width,canvas.height);image.close();const jpg=canvas.toDataURL('image/jpeg',.85);setPreview(jpg)
   const {createWorker}=await import('tesseract.js');const worker=await createWorker('ita',1,{logger:status=>{if(status.status==='recognizing text')setMessage(`Lettura foto ${Math.round(status.progress*100)}%`);else setMessage('Preparazione lettura foto: il primo avvio richiede internet.') }})
   try{const result=await worker.recognize(jpg);setDraft(parseInvoicePhotoText(result.data.text));setMessage('Foto letta: verifica tutti i dati. Il fornitore e gli importi delle singole righe richiedono conferma.')}finally{await worker.terminate()}
  }catch(error){setMessage(error instanceof Error?error.message:'Lettura non riuscita. Puoi usare il modulo manuale della fattura fornitore.')}finally{setBusy(false)}
 }
 const save=()=>{if(!draft)return;try{
  if(!draft.supplierName.trim()||!draft.invoiceNumber.trim()||!draft.invoiceDate||draft.totalAmount<=0)throw new Error('Completa fornitore, numero, data e totale.')
  const validDate=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(`${value}T12:00:00Z`).toISOString().slice(0,10)===value
  if(!validDate(draft.invoiceDate)||draft.installments.some(item=>!validDate(item.dueDate)))throw new Error('Controlla la data fattura e le scadenze.')
  if([draft.taxableAmount,draft.vatAmount,draft.totalAmount,...draft.costLines.map(line=>line.amount)].some(value=>!Number.isFinite(value)||value<0)||Math.abs(draft.taxableAmount+draft.vatAmount-draft.totalAmount)>.02)throw new Error('Imponibile più IVA deve corrispondere al totale. Per ritenute o altri importi usa il modulo manuale.')
  if(draft.installments.some(item=>!item.dueDate||item.amount<=0)||Math.abs(draft.installments.reduce((sum,item)=>sum+item.amount,0)-draft.totalAmount)>.02)throw new Error('Completa le scadenze: la somma delle rate deve corrispondere al totale.')
  if((data.payables??[]).some(item=>item.kind==='supplier-invoice'&&item.invoiceNumber?.toLowerCase()===draft.invoiceNumber.trim().toLowerCase()&&item.supplierName?.toLowerCase()===draft.supplierName.trim().toLowerCase()))throw new Error('Questa fattura è già registrata per il fornitore.')
  onSave({kind:'supplier-invoice',category:'fornitori',description:`Fattura ${draft.invoiceNumber}`,supplierName:draft.supplierName,invoiceNumber:draft.invoiceNumber,invoiceDate:draft.invoiceDate,taxableAmount:draft.taxableAmount,vatAmount:draft.vatAmount,totalAmount:draft.totalAmount,paymentMethod:draft.installments[0].method,dueDate:draft.installments[0].dueDate,vatDeductibilityMode:'none',costLines:draft.costLines,notes:'Importazione documento confermata. Deducibilità IVA da verificare con il commercialista.',installments:draft.installments.map((item,index)=>({installmentNo:index+1,amount:item.amount,dueDate:item.dueDate,note:'Importata dal documento e confermata'}))});setDraft(null);setPreview('');setMessage('Fattura registrata nello scadenziario con avvisi a 15 giorni.')
 }catch(error){setMessage(error instanceof Error?error.message:'Registrazione non riuscita.') }}
 return <section className="panel"><h3>Registra fattura da XML o foto</h3><p>Preferisci l’XML della fattura elettronica: contiene righe e scadenze strutturate. La foto viene letta sul dispositivo; controlla i dati prima di confermare.</p><label>Carica XML o fotografia<input type="file" accept=".xml,image/jpeg,image/png,image/webp" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void read(file);event.target.value=''}} /></label><p role="status">{message}</p>{preview&&<img src={preview} alt="Documento da controllare" style={{maxWidth:'100%',maxHeight:300}} />}
 {draft&&<div className="form-grid"><label>Fornitore<input value={draft.supplierName} onChange={e=>setDraft({...draft,supplierName:e.target.value})} /></label><label>Numero fattura<input value={draft.invoiceNumber} onChange={e=>setDraft({...draft,invoiceNumber:e.target.value})} /></label><label>Data fattura<input type="date" value={draft.invoiceDate} onChange={e=>setDraft({...draft,invoiceDate:e.target.value})} /></label><label>Imponibile<MoneyInput value={draft.taxableAmount} onValueChange={value=>setDraft({...draft,taxableAmount:value ?? 0})} /></label><label>IVA<MoneyInput value={draft.vatAmount} onValueChange={value=>setDraft({...draft,vatAmount:value ?? 0})} /></label><label>Totale<MoneyInput value={draft.totalAmount} onValueChange={value=>setDraft({...draft,totalAmount:value ?? 0})} /></label>
 {draft.costLines.map((line,index)=><label className="full" key={index}>{line.description}<MoneyInput value={line.amount} onValueChange={amount=>setDraft({...draft,costLines:draft.costLines.map((item,i)=>i===index?{...item,amount:amount ?? 0}:item)})} /><select value={line.category} onChange={e=>setDraft({...draft,costLines:draft.costLines.map((item,i)=>i===index?{...item,category:e.target.value as SupplierCostCategory}:item)})}>{['Ricambi','Materiali di consumo','Lavorazioni esterne','Altri costi'].map(category=><option key={category}>{category}</option>)}</select></label>)}
 {(draft.installments.length?draft.installments:[{amount:draft.totalAmount,dueDate:'',method:'Bonifico' as const}]).map((item,index)=><div className="full" key={index}><label>Scadenza rata {index+1}<input type="date" value={item.dueDate} onChange={e=>{const rows=draft.installments.length?[...draft.installments]:[item];rows[index]={...item,dueDate:e.target.value};setDraft({...draft,installments:rows})}} /></label><label>Metodo pagamento<select value={item.method} onChange={e=>{const rows=draft.installments.length?[...draft.installments]:[item];rows[index]={...item,method:e.target.value as PaymentMethod};setDraft({...draft,installments:rows})}}>{['Bonifico','Contanti','POS','R.I.B.A.','Personalizzato'].map(method=><option key={method}>{method}</option>)}</select></label><label>Importo rata<MoneyInput value={item.amount} onValueChange={value=>{const amount=value ?? 0; const rows=draft.installments.length?[...draft.installments]:[item];rows[index]={...item,amount};setDraft({...draft,installments:rows})}} /></label></div>)}
 <p className="full">La registrazione crea una fattura da pagare. Non registra pagamenti né assegna costi a una vettura. Deducibilità IVA da verificare nel dettaglio della fattura.</p><button type="button" onClick={save}>Conferma e registra nello scadenziario</button><button type="button" onClick={()=>{setDraft(null);setPreview('')}}>Annulla</button></div>}
 </section>
}
