import { describe, expect, it } from 'vitest'
import { parseSupplierInvoiceXml, parseInvoicePhotoText, supplierCostCategory } from './supplierInvoiceImport'
const xml=`<FatturaElettronica><FatturaElettronicaHeader><CedentePrestatore><DatiAnagrafici><Anagrafica><Denominazione>Fornitore</Denominazione></Anagrafica></DatiAnagrafici></CedentePrestatore></FatturaElettronicaHeader><FatturaElettronicaBody><DatiGenerali><DatiGeneraliDocumento><TipoDocumento>TD01</TipoDocumento><Divisa>EUR</Divisa><Data>2026-10-04</Data><Numero>123</Numero><ImportoTotaleDocumento>122.00</ImportoTotaleDocumento></DatiGeneraliDocumento></DatiGenerali><DatiBeniServizi><DettaglioLinee><Descrizione>Paraurti anteriore</Descrizione><PrezzoTotale>100.00</PrezzoTotale></DettaglioLinee><DatiRiepilogo><ImponibileImporto>100.00</ImponibileImporto><Imposta>22.00</Imposta></DatiRiepilogo></DatiBeniServizi><DatiPagamento><DettaglioPagamento><ModalitaPagamento>MP05</ModalitaPagamento><DataScadenzaPagamento>2026-11-30</DataScadenzaPagamento><ImportoPagamento>122.00</ImportoPagamento></DettaglioPagamento></DatiPagamento></FatturaElettronicaBody></FatturaElettronica>`
describe('importazione fatture',()=>{
 it('legge il cedente, importi e rate e classifica il ricambio',()=>{const d=parseSupplierInvoiceXml(xml);expect(d.supplierName).toBe('Fornitore');expect(d.totalAmount).toBe(122);expect(d.installments[0].dueDate).toBe('2026-11-30');expect(d.costLines[0].category).toBe('Ricambi')})
 it('rifiuta documenti ambigui, crediti e pagamenti discordanti',()=>{expect(()=>parseSupplierInvoiceXml(xml.replace('TD01','TD04'))).toThrow('Tipo documento');expect(()=>parseSupplierInvoiceXml(xml.replace('<ImportoPagamento>122.00','<ImportoPagamento>100.00'))).toThrow('diversi');expect(()=>parseSupplierInvoiceXml('<!DOCTYPE x><x/>')).toThrow('XML non supportato')})
 it('legge testo fotografato senza inventare fornitore o scadenza',()=>{const d=parseInvoicePhotoText('Fattura n. 125\nData fattura: 04/10/2026\nTotale documento 1.220,00\nImponibile 1.000,00\nTotale IVA 220,00');expect(d.totalAmount).toBe(1220);expect(d.invoiceDate).toBe('2026-10-04');expect(d.supplierName).toBe('');expect(d.installments[0].dueDate).toBe('')})
 it('distingue materiali e costi esterni',()=>{expect(supplierCostCategory('Vernice e diluente')).toBe('Materiali di consumo');expect(supplierCostCategory('Lavorazione esterna')).toBe('Lavorazioni esterne')})
})
