import type { ErpData, Vehicle } from '../../types'
import { changeVehicleStatus } from '../../services/erp'

export const PHASES = ['Accettata','In attesa autorizzazione','Ricambi da ordinare','In attesa ricambi','Smontaggio','Lattoneria','Preparazione','Verniciatura','Montaggio','Lucidatura','Lavaggio','Controllo qualità','Pronta consegna','Consegnata','Sospesa'] as const
export type ProductionPhase = typeof PHASES[number]
export type Priority = 'Normale'|'Alta'|'Urgente'
export type PartStatus = 'Da ordinare'|'Ordinato'|'Arrivato'|'Errato'|'Reso'
export interface PhaseEvent { id:string; vehicleId:string; from:ProductionPhase; to:ProductionPhase; at:string; operator:string; note:string; suspensionReason:string }
export interface TimeEntry { id:string; vehicleId:string; phase:ProductionPhase; operatorId:string; startedAt:string; stoppedAt:string; minutes:number; correctionReason:string }
export interface Part { id:string; vehicleId:string; description:string; status:PartStatus; supplier:string; orderDate:string; expectedDate:string; cost:number; notes:string }
export interface Block { id:string; vehicleId:string; type:string; openedAt:string; owner:string; action:string; expectedUnlock:string; closedAt:string }
export interface QualityCheck { key:string; label:string; required:boolean; done:boolean }
export interface ProductionJob { vehicleId:string; phase:ProductionPhase; priority:Priority; promisedDate:string; ownerId:string; estimatedHours:number; notes:string; authorization:'Da richiedere'|'Richiesta'|'Autorizzata'|'Negata'; quality:QualityCheck[]; reopenedAt:string }
export interface Operator { id:string; name:string; role:string; dailyHours:number; skills:ProductionPhase[]; active:boolean }
export interface PlanItem { id:string; vehicleId:string; operatorId:string; date:string; hours:number; phase:ProductionPhase; manual:boolean; originalHours:number }
export interface ProductionState { version:1; jobs:ProductionJob[]; phaseHistory:PhaseEvent[]; timeEntries:TimeEntry[]; parts:Part[]; blocks:Block[]; operators:Operator[]; plan:PlanItem[] }

const DB='carrozzeria-elias-production'; const STORE='state'; const KEY='current'
export const emptyProduction:ProductionState={version:1,jobs:[],phaseHistory:[],timeEntries:[],parts:[],blocks:[],operators:[],plan:[]}
const uid=()=>crypto.randomUUID(); const now=()=>new Date().toISOString()
const defaultQuality=():QualityCheck[]=>[
 ['montaggio','Montaggio completato'],['componenti','Funzionamento componenti verificato'],['lucidatura','Lucidatura completata'],['pulizia','Pulizia interna/esterna'],['spie','Assenza spie'],['foto','Fotografie finali'],['documenti','Documenti pronti'],['responsabile','Controllo responsabile']
].map(([key,label])=>({key,label,required:true,done:false}))

function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function loadProduction():Promise<ProductionState>{try{const db=await openDb();const value=await new Promise<ProductionState|undefined>((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get(KEY);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();return value?{...emptyProduction,...value}:structuredClone(emptyProduction)}catch{return structuredClone(emptyProduction)}}
export async function saveProduction(state:ProductionState){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(structuredClone(state),KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
export function ensureJobs(state:ProductionState,vehicles:Vehicle[]):ProductionState{const known=new Set(state.jobs.map(j=>j.vehicleId));const jobs=[...state.jobs];for(const v of vehicles)if(!known.has(v.id)&&v.status!=='Consegnata')jobs.push({vehicleId:v.id,phase:v.status==='Accettata'?'Accettata':'Smontaggio',priority:v.priority??'Normale',promisedDate:v.requestedDeliveryDate||v.deliveryDate||'',ownerId:'',estimatedHours:v.estimatedHours||0,notes:'',authorization:'Da richiedere',quality:defaultQuality(),reopenedAt:''});return {...state,jobs}}
export function movePhase(state:ProductionState,vehicleId:string,to:ProductionPhase,operator:string,note='',suspensionReason=''){const job=state.jobs.find(j=>j.vehicleId===vehicleId);if(!job)throw new Error('Scheda produzione non trovata.');if(job.phase==='Consegnata'&&!job.reopenedAt)throw new Error('La vettura consegnata deve essere riaperta con tracciatura.');if(to==='Pronta consegna'&&job.quality.some(q=>q.required&&!q.done))throw new Error('Completa la checklist qualità prima della pronta consegna.');const event:PhaseEvent={id:uid(),vehicleId,from:job.phase,to,at:now(),operator,note,suspensionReason};return {...state,jobs:state.jobs.map(j=>j.vehicleId===vehicleId?{...j,phase:to}:j),phaseHistory:[event,...state.phaseHistory]}}
export function reopenJob(state:ProductionState,vehicleId:string,operator:string,reason:string){if(!reason.trim())throw new Error('Motivazione obbligatoria.');const job=state.jobs.find(j=>j.vehicleId===vehicleId);if(!job||job.phase!=='Consegnata')throw new Error('Solo una vettura consegnata può essere riaperta.');const next={...state,jobs:state.jobs.map(j=>j.vehicleId===vehicleId?{...j,reopenedAt:now(),phase:'Accettata' as const}:j)};return {...next,phaseHistory:[{id:uid(),vehicleId,from:'Consegnata',to:'Accettata',at:now(),operator,note:reason,suspensionReason:''},...next.phaseHistory]}}
export function startTimer(state:ProductionState,vehicleId:string,phase:ProductionPhase,operatorId:string){if(state.timeEntries.some(t=>t.operatorId===operatorId&&!t.stoppedAt))throw new Error('L’operatore ha già un timer attivo.');return {...state,timeEntries:[{id:uid(),vehicleId,phase,operatorId,startedAt:now(),stoppedAt:'',minutes:0,correctionReason:''},...state.timeEntries]}}
export function stopTimer(state:ProductionState,entryId:string){const end=Date.now();return {...state,timeEntries:state.timeEntries.map(t=>t.id===entryId?{...t,stoppedAt:new Date(end).toISOString(),minutes:Math.max(1,Math.round((end-new Date(t.startedAt).getTime())/60000))}:t)}}
export function correctTime(state:ProductionState,entryId:string,minutes:number,reason:string){if(minutes<0)throw new Error('Il tempo non può essere negativo.');if(!reason.trim())throw new Error('La correzione richiede una motivazione.');return {...state,timeEntries:state.timeEntries.map(t=>t.id===entryId?{...t,minutes,correctionReason:reason}:t)}}
export const workedHours=(state:ProductionState,vehicleId:string)=>state.timeEntries.filter(t=>t.vehicleId===vehicleId).reduce((s,t)=>s+t.minutes,0)/60
export function deliveryRisk(state:ProductionState,job:ProductionJob,today=new Date()){if(job.phase==='Consegnata')return 'Completata';const due=job.promisedDate?new Date(job.promisedDate+'T23:59:59'):null;if(due&&due<today)return 'In ritardo';const remaining=Math.max(0,job.estimatedHours-workedHours(state,job.vehicleId));const missingParts=state.parts.some(p=>p.vehicleId===job.vehicleId&&!['Arrivato','Reso'].includes(p.status));const blocked=state.blocks.some(b=>b.vehicleId===job.vehicleId&&!b.closedAt);const auth=job.authorization!=='Autorizzata';const days=due?Math.max(0,Math.ceil((due.getTime()-today.getTime())/86400000)):99;return missingParts||blocked||auth||remaining>days*8?'A rischio':'Regolare'}
export function operatorLoad(state:ProductionState,operatorId:string,date:string){return state.plan.filter(p=>p.operatorId===operatorId&&p.date===date).reduce((s,p)=>s+p.hours,0)}
export function addPlan(state:ProductionState,item:Omit<PlanItem,'id'|'originalHours'>){const op=state.operators.find(o=>o.id===item.operatorId);if(!op)throw new Error('Operatore non trovato.');const load=operatorLoad(state,item.operatorId,item.date);if(load+item.hours>op.dailyHours)throw new Error(`Sovraccarico: capacità ${op.dailyHours} ore, pianificate ${load+item.hours}.`);return {...state,plan:[...state.plan,{...item,id:uid(),originalHours:item.hours}]}}
export function addPart(state:ProductionState,part:Omit<Part,'id'>){return {...state,parts:[{...part,id:uid()},...state.parts]}}
export function addBlock(state:ProductionState,block:Omit<Block,'id'|'openedAt'|'closedAt'>){return {...state,blocks:[{...block,id:uid(),openedAt:now(),closedAt:''},...state.blocks]}}
export function toggleQuality(state:ProductionState,vehicleId:string,key:string){return {...state,jobs:state.jobs.map(j=>j.vehicleId===vehicleId?{...j,quality:j.quality.map(q=>q.key===key?{...q,done:!q.done}:q)}:j)}}
export function deliverVehicle(state:ProductionState,erp:ErpData,vehicleId:string,operator:string,derogation=''):{production:ProductionState;erp:ErpData}{const job=state.jobs.find(j=>j.vehicleId===vehicleId);if(!job)throw new Error('Scheda non trovata.');const missing=job.quality.some(q=>q.required&&!q.done);if(missing&&!derogation.trim())throw new Error('Checklist incompleta: inserisci una deroga motivata.');const production=movePhase(state,vehicleId,'Consegnata',operator,derogation);return {production,erp:changeVehicleStatus(erp,vehicleId,'Consegnata')}}
