import { useEffect, useMemo, useState } from 'react'
import { loadDatabase, saveDatabase } from '../../services/database'
import type { ErpData } from '../../types'
import { PHASES, deliveryRisk, deliverVehicle, ensureJobs, loadProduction, movePhase, saveProduction, startTimer, stopTimer, toggleQuality, workedHours, type ProductionPhase, type ProductionState } from './production'

const today=()=>new Date().toISOString().slice(0,10)
export function ProductionPage(){
 const [erp,setErp]=useState<ErpData|null>(null); const [state,setState]=useState<ProductionState|null>(null); const [query,setQuery]=useState(''); const [priority,setPriority]=useState(''); const [selected,setSelected]=useState(''); const [message,setMessage]=useState('')
 useEffect(()=>{Promise.all([loadDatabase(),loadProduction()]).then(([e,p])=>{const next=ensureJobs(p,e.vehicles);setErp(e);setState(next);void saveProduction(next)})},[])
 const persist=(next:ProductionState)=>{setState(next);void saveProduction(next)}
 const rows=useMemo(()=>{if(!erp||!state)return[];return state.jobs.map(job=>({job,vehicle:erp.vehicles.find(v=>v.id===job.vehicleId),customer:erp.customers.find(c=>c.id===erp.vehicles.find(v=>v.id===job.vehicleId)?.customerId)})).filter(r=>r.vehicle&&(r.vehicle.plate+r.vehicle.make+r.vehicle.model).toLowerCase().includes(query.toLowerCase())&&(!priority||r.job.priority===priority))},[erp,state,query,priority])
 if(!erp||!state)return <main className="app-shell"><h2>Caricamento produzione…</h2></main>
 const selectedJob=state.jobs.find(j=>j.vehicleId===selected); const selectedVehicle=erp.vehicles.find(v=>v.id===selected)
 const active=state.timeEntries.find(t=>!t.stoppedAt)
 const change=(vehicleId:string,phase:ProductionPhase)=>{try{persist(movePhase(state,vehicleId,phase,'Titolare'));setMessage('Fase aggiornata e registrata nello storico.')}catch(e){setMessage((e as Error).message)}}
 const deliver=()=>{try{const result=deliverVehicle(state,erp,selected,'Titolare');persist(result.production);setErp(result.erp);void saveDatabase(result.erp);setMessage('Vettura consegnata, cono liberato e stato finanziario impostato su Da fatturare.')}catch(e){setMessage((e as Error).message)}}
 return <main style={{padding:24,fontFamily:'Inter,system-ui',background:'#0e1116',color:'#f4f4f4',minHeight:'100vh'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><small>CARROZZERIA ELIAS ERP</small><h1>Controllo produzione</h1></div><a href="/" style={{color:'#fff'}}>← Gestionale</a></header>
  {message&&<p style={{padding:12,background:'#202833',borderRadius:10}}>{message}</p>}
  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12,margin:'18px 0'}}>
   <Stat label="Vetture presenti" value={state.jobs.filter(j=>j.phase!=='Consegnata').length}/><Stat label="In ritardo" value={state.jobs.filter(j=>deliveryRisk(state,j)==='In ritardo').length}/><Stat label="A rischio" value={state.jobs.filter(j=>deliveryRisk(state,j)==='A rischio').length}/><Stat label="Bloccate" value={state.blocks.filter(b=>!b.closedAt).length}/><Stat label="Coni occupati" value={erp.vehicles.filter(v=>v.coneNumber!==null).length}/><Stat label="Timer attivi" value={state.timeEntries.filter(t=>!t.stoppedAt).length}/>
  </section>
  <section style={{display:'flex',gap:10,marginBottom:16,flexWrap:'wrap'}}><input placeholder="Cerca targa o modello" value={query} onChange={e=>setQuery(e.target.value)} style={input}/><select value={priority} onChange={e=>setPriority(e.target.value)} style={input}><option value="">Tutte le priorità</option><option>Normale</option><option>Alta</option><option>Urgente</option></select></section>
  <section style={{overflowX:'auto',display:'flex',gap:12,paddingBottom:18}}>{PHASES.map(phase=>{const cards=rows.filter(r=>r.job.phase===phase);return <div key={phase} style={{minWidth:260,background:'#171c23',borderRadius:14,padding:12}}><h3>{phase} · {cards.length}</h3><small>{cards.reduce((s,r)=>s+Math.max(0,r.job.estimatedHours-workedHours(state,r.job.vehicleId)),0).toFixed(1)} ore residue</small>{cards.map(({job,vehicle,customer})=><article key={job.vehicleId} onClick={()=>setSelected(job.vehicleId)} style={{background:selected===job.vehicleId?'#324153':'#222a34',padding:12,borderRadius:10,marginTop:10,cursor:'pointer'}}><strong>{vehicle!.plate} · {vehicle!.make} {vehicle!.model}</strong><p>{customer?.name||'Cliente'} · {job.priority}</p><p>Consegna: {job.promisedDate||'non definita'} · <b>{deliveryRisk(state,job)}</b></p><select value={job.phase} onClick={e=>e.stopPropagation()} onChange={e=>change(job.vehicleId,e.target.value as ProductionPhase)} style={input}>{PHASES.map(p=><option key={p}>{p}</option>)}</select></article>)}</div>})}</section>
  {selectedJob&&selectedVehicle&&<section style={{background:'#171c23',borderRadius:14,padding:18}}><h2>Scheda {selectedVehicle.plate}</h2><p>Ore stimate {selectedJob.estimatedHours} · effettuate {workedHours(state,selected).toFixed(1)} · residue {Math.max(0,selectedJob.estimatedHours-workedHours(state,selected)).toFixed(1)}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{selectedJob.quality.map(q=><label key={q.key} style={{padding:8,background:'#222a34',borderRadius:8}}><input type="checkbox" checked={q.done} onChange={()=>persist(toggleQuality(state,selected,q.key))}/> {q.label}</label>)}</div><div style={{display:'flex',gap:8,marginTop:14,flexWrap:'wrap'}}>{active?<button onClick={()=>persist(stopTimer(state,active.id))}>Ferma timer</button>:<button onClick={()=>{try{persist(startTimer(state,selected,selectedJob.phase,'titolare'))}catch(e){setMessage((e as Error).message)}}>Avvia timer</button>}<button onClick={deliver}>Consegna vettura</button></div></section>}
  <section style={{marginTop:18}}><h2>Consegne</h2>{state.jobs.filter(j=>j.promisedDate&&j.promisedDate<=today()&&j.phase!=='Consegnata').map(j=><p key={j.vehicleId}>{erp.vehicles.find(v=>v.id===j.vehicleId)?.plate} · {j.promisedDate} · {deliveryRisk(state,j)}</p>)}</section>
 </main>
}
const input={background:'#10151b',color:'#fff',border:'1px solid #3a4655',padding:'10px',borderRadius:8} as const
function Stat({label,value}:{label:string,value:string|number}){return <div style={{background:'#171c23',padding:14,borderRadius:12}}><small>{label}</small><div style={{fontSize:28,fontWeight:700}}>{value}</div></div>}
